version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
      interval: 10s
      retries: 10
    restart: always

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: jobs
    ports:
      - "5433:5433"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "5434:5434"
    restart: always

  scrapy:
    build:
      dockerfile: dockerfile
    ports:
      - "5431:5431"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_started
        restart: true
      redis:
        condition: service_started
        restart: true
